SELECT TOP (1000) [ventas_hoy]
      ,[pedidos_hoy]
      ,[ticket_promedio_hoy]
      ,[ventas_mes]
      ,[pedidos_mes]
      ,[plato_top_hoy]
      ,[mesas_ocupadas]
      ,[pedidos_pendientes]
      ,[ultima_actualizacion]
  FROM [EsbirrosDB].[dbo].[vw_DashboardEjecutivo]
