SELECT TOP (100) [mesa_id]
      ,[mesa_numero]
      ,[capacidad]
      ,[qr_token]
      ,[sucursal_id]
      ,[sucursal_nombre]
      ,[estado_actual]
      ,[pedido_activo_id]
      ,[pedido_inicio]
      ,[cant_comensales]
      ,[total]
      ,[estado_pedido_activo]
      ,[empleado_responsable]
      ,[minutos_ocupada]
      ,[estado_operativo]
  FROM [EsbirrosDB].[dbo].[vw_EstadoMesas]
