SELECT TOP (1000) [tipo_monitoreo]
      ,[momento]
      ,[pendientes]
      ,[confirmados]
      ,[en_preparacion]
      ,[listos_entrega]
      ,[en_reparto]
      ,[mesas_ocupadas]
      ,[mesas_totales]
      ,[ventas_acumuladas_hoy]
      ,[empleados_activos_hoy]
  FROM [EsbirrosDB].[dbo].[vw_MonitoreoTiempoReal]
