SELECT TOP (1000) [pedido_id]
      ,[fecha_pedido]
      ,[fecha_pedido_formato]
      ,[hora_pedido]
      ,[dia_semana]
      ,[estado_nombre]
      ,[estado_orden]
      ,[canal_nombre]
      ,[cliente_id]
      ,[cliente_nombre]
      ,[cliente_telefono]
      ,[cliente_email]
      ,[mesa_id]
      ,[mesa_numero]
      ,[mesa_capacidad]
      ,[cant_comensales]
      ,[empleado_id]
      ,[empleado_nombre]
      ,[empleado_usuario]
      ,[sucursal_id]
      ,[sucursal_nombre]
      ,[sucursal_direccion]
      ,[total_pedido]
      ,[fecha_entrega]
      ,[minutos_transcurridos]
  FROM [EsbirrosDB].[dbo].[vw_PedidosCompletos]
  ORDER BY fecha_pedido DESC
